//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PackageEntities : DbContext
{
    public PackageEntities()
        : base("name=PackageEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Accommodation> Accommodations { get; set; }
    public virtual DbSet<BotConversation> BotConversations { get; set; }
    public virtual DbSet<DiscountPackage> DiscountPackages { get; set; }
    public virtual DbSet<Hotel> Hotels { get; set; }
    public virtual DbSet<HotelFacility> HotelFacilities { get; set; }
    public virtual DbSet<HotelImage> HotelImages { get; set; }
    public virtual DbSet<PackageItenryDetail> PackageItenryDetails { get; set; }
    public virtual DbSet<Ziarat> Ziarats { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<TransPort> TransPorts { get; set; }
    public virtual DbSet<AirLine> AirLines { get; set; }
    public virtual DbSet<Flight> Flights { get; set; }
    public virtual DbSet<VisaPackage> VisaPackages { get; set; }
    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
    public virtual DbSet<AlharmainUser> AlharmainUsers { get; set; }
    public virtual DbSet<CustomFlightConfiguration> CustomFlightConfigurations { get; set; }
    public virtual DbSet<CustomHotelConfiguration> CustomHotelConfigurations { get; set; }
    public virtual DbSet<CustomPackage> CustomPackages { get; set; }
    public virtual DbSet<AlharmainUserPackage> AlharmainUserPackages { get; set; }
    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    public virtual DbSet<ChatAdmin> ChatAdmins { get; set; }
    public virtual DbSet<DreamLayout> DreamLayouts { get; set; }
    public virtual DbSet<InviteSharePage> InviteSharePages { get; set; }
    public virtual DbSet<Multimediabank> Multimediabanks { get; set; }
    public virtual DbSet<Tag> Tags { get; set; }
    public virtual DbSet<VideoTranscript> VideoTranscripts { get; set; }
    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
    public virtual DbSet<PackageType> PackageTypes { get; set; }
    public virtual DbSet<PackageTag> PackageTags { get; set; }
    public virtual DbSet<Package> Packages { get; set; }
    public virtual DbSet<MediaCategory> MediaCategories { get; set; }
    public virtual DbSet<MediaGroup> MediaGroups { get; set; }
    public virtual DbSet<MediaItem> MediaItems { get; set; }
    public virtual DbSet<MediaTag> MediaTags { get; set; }
    public virtual DbSet<PackageDetail> PackageDetails { get; set; }
}
