//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Accommodation
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Accommodation()
    {
        this.AlharmainUserPackages = new HashSet<AlharmainUserPackage>();
        this.AlharmainUserPackages1 = new HashSet<AlharmainUserPackage>();
    }

    public int id { get; set; }
    public string Name { get; set; }
    public double price { get; set; }
    public bool availability { get; set; }
    public int hotelID { get; set; }

    public virtual Hotel Hotel { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AlharmainUserPackage> AlharmainUserPackages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AlharmainUserPackage> AlharmainUserPackages1 { get; set; }
}

public partial class AirLine
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AirLine()
    {
        this.Flights = new HashSet<Flight>();
        this.CustomFlightConfigurations = new HashSet<CustomFlightConfiguration>();
    }

    public int id { get; set; }
    public string Name { get; set; }
    public string AspNetUserID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Flight> Flights { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CustomFlightConfiguration> CustomFlightConfigurations { get; set; }
    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class AlharmainUser
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AlharmainUser()
    {
        this.AlharmainUserPackages = new HashSet<AlharmainUserPackage>();
    }

    public int id { get; set; }
    public string Name { get; set; }
    public string mobileNo { get; set; }
    public string email { get; set; }
    public string contect { get; set; }
    public string city { get; set; }
    public string province { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AlharmainUserPackage> AlharmainUserPackages { get; set; }
}

public partial class AlharmainUserPackage
{
    public long id { get; set; }
    public Nullable<int> userID { get; set; }
    public Nullable<int> packageDetailID { get; set; }
    public bool isCustomPackage { get; set; }
    public Nullable<int> discountID { get; set; }
    public Nullable<int> AccomMakkahID { get; set; }
    public Nullable<int> AccomMadinaID { get; set; }
    public int adults { get; set; }
    public int children { get; set; }
    public int infants { get; set; }
    public string trackingID { get; set; }
    public bool IsAmountRecieved { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public Nullable<int> CustomPackageId { get; set; }

    public virtual Accommodation Accommodation { get; set; }
    public virtual Accommodation Accommodation1 { get; set; }
    public virtual AlharmainUser AlharmainUser { get; set; }
    public virtual CustomPackage CustomPackage { get; set; }
    public virtual DiscountPackage DiscountPackage { get; set; }
    public virtual PackageDetail PackageDetail { get; set; }
}

public partial class AspNetRole
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AspNetRole()
    {
        this.AspNetUsers = new HashSet<AspNetUser>();
    }

    public string Id { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
}

public partial class AspNetUser
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AspNetUser()
    {
        this.AirLines = new HashSet<AirLine>();
        this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
        this.Hotels = new HashSet<Hotel>();
        this.VisaPackages = new HashSet<VisaPackage>();
        this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
        this.AspNetRoles = new HashSet<AspNetRole>();
        this.Packages = new HashSet<Package>();
    }

    public string Id { get; set; }
    public string Email { get; set; }
    public bool EmailConfirmed { get; set; }
    public string PasswordHash { get; set; }
    public string SecurityStamp { get; set; }
    public string PhoneNumber { get; set; }
    public bool PhoneNumberConfirmed { get; set; }
    public bool TwoFactorEnabled { get; set; }
    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
    public bool LockoutEnabled { get; set; }
    public int AccessFailedCount { get; set; }
    public string UserName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AirLine> AirLines { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Hotel> Hotels { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VisaPackage> VisaPackages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Package> Packages { get; set; }
}

public partial class AspNetUserClaim
{
    public int Id { get; set; }
    public string UserId { get; set; }
    public string ClaimType { get; set; }
    public string ClaimValue { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class AspNetUserLogin
{
    public string LoginProvider { get; set; }
    public string ProviderKey { get; set; }
    public string UserId { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class BotConversation
{
    public int id { get; set; }
    public string question { get; set; }
    public string answer { get; set; }
    public string functionName { get; set; }
}

public partial class ChatAdmin
{
    public int id { get; set; }
    public string tokenID { get; set; }
    public string serverID { get; set; }
    public int layoutID { get; set; }

    public virtual DreamLayout DreamLayout { get; set; }
}

public partial class CustomFlightConfiguration
{
    public int id { get; set; }
    public int AirLineID { get; set; }
    public int Class { get; set; }
    public decimal EstimatedPrice { get; set; }
    public System.DateTime Month { get; set; }
    public bool IsRoundTrip { get; set; }

    public virtual AirLine AirLine { get; set; }
}

public partial class CustomHotelConfiguration
{
    public int id { get; set; }
    public int Rating { get; set; }
    public string AccommodationType { get; set; }
    public long Distance { get; set; }
    public decimal EstimatedPrice { get; set; }
    public System.DateTime Month { get; set; }
    public string HotelCity { get; set; }
}

public partial class CustomPackage
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CustomPackage()
    {
        this.AlharmainUserPackages = new HashSet<AlharmainUserPackage>();
    }

    public int id { get; set; }
    public int month { get; set; }
    public int MakkahRating { get; set; }
    public int nightsMakkah { get; set; }
    public int MadinaRating { get; set; }
    public int nightsMadina { get; set; }
    public bool isRoundTrip { get; set; }
    public decimal MakkahDistance { get; set; }
    public decimal MadinaDistance { get; set; }
    public string MakkahAccom { get; set; }
    public string MadinaAccom { get; set; }
    public int airlineID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AlharmainUserPackage> AlharmainUserPackages { get; set; }
}

public partial class DiscountPackage
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DiscountPackage()
    {
        this.AlharmainUserPackages = new HashSet<AlharmainUserPackage>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public System.DateTime availableFrom { get; set; }
    public System.DateTime availableTill { get; set; }
    public int packageDetailID { get; set; }
    public double discountPercent { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AlharmainUserPackage> AlharmainUserPackages { get; set; }
    public virtual PackageDetail PackageDetail { get; set; }
}

public partial class DreamLayout
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DreamLayout()
    {
        this.ChatAdmins = new HashSet<ChatAdmin>();
        this.InviteSharePages = new HashSet<InviteSharePage>();
    }

    public int id { get; set; }
    public string Layout { get; set; }
    public Nullable<int> DreamID { get; set; }
    public string Page { get; set; }
    public string Description { get; set; }
    public string LayoutType { get; set; }
    public bool IsPublished { get; set; }
    public Nullable<bool> IsUserDefaultPage { get; set; }
    public bool IsPublicDefaultPage { get; set; }
    public Nullable<bool> IsActive { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ChatAdmin> ChatAdmins { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<InviteSharePage> InviteSharePages { get; set; }
    public virtual Package Package { get; set; }
}

public partial class Flight
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Flight()
    {
        this.PackageDetails = new HashSet<PackageDetail>();
        this.PackageDetails1 = new HashSet<PackageDetail>();
    }

    public int id { get; set; }
    public string Name { get; set; }
    public System.DateTime departureDate { get; set; }
    public System.DateTime returnDate { get; set; }
    public string fromCity { get; set; }
    public string destinationCity { get; set; }
    public double price { get; set; }
    public int flightType { get; set; }
    public int airLineID { get; set; }

    public virtual AirLine AirLine { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageDetail> PackageDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageDetail> PackageDetails1 { get; set; }
}

public partial class Hotel
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Hotel()
    {
        this.Accommodations = new HashSet<Accommodation>();
        this.HotelFacilities = new HashSet<HotelFacility>();
        this.HotelImages = new HashSet<HotelImage>();
        this.PackageItenryDetails = new HashSet<PackageItenryDetail>();
        this.PackageDetails = new HashSet<PackageDetail>();
        this.PackageDetails1 = new HashSet<PackageDetail>();
    }

    public int id { get; set; }
    public string hotelName { get; set; }
    public string description { get; set; }
    public int rating { get; set; }
    public double distance { get; set; }
    public int mediaID { get; set; }
    public string AspNetUserID { get; set; }
    public string hotelType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Accommodation> Accommodations { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HotelFacility> HotelFacilities { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HotelImage> HotelImages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageItenryDetail> PackageItenryDetails { get; set; }
    public virtual AspNetUser AspNetUser { get; set; }
    public virtual MediaItem MediaItem { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageDetail> PackageDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageDetail> PackageDetails1 { get; set; }
}

public partial class HotelFacility
{
    public int id { get; set; }
    public string Name { get; set; }
    public bool availability { get; set; }
    public int mediaID { get; set; }
    public int hotelID { get; set; }

    public virtual Hotel Hotel { get; set; }
    public virtual MediaItem MediaItem { get; set; }
}

public partial class HotelImage
{
    public int id { get; set; }
    public int mediaID { get; set; }
    public int hotelID { get; set; }

    public virtual Hotel Hotel { get; set; }
    public virtual MediaItem MediaItem { get; set; }
}

public partial class InviteSharePage
{
    public int id { get; set; }
    public int LayoutID { get; set; }
    public string shareText { get; set; }
    public string shareURL { get; set; }

    public virtual DreamLayout DreamLayout { get; set; }
}

public partial class MediaCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MediaCategory()
    {
        this.MediaItems = new HashSet<MediaItem>();
    }

    public int id { get; set; }
    public string CategoryName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MediaItem> MediaItems { get; set; }
}

public partial class MediaGroup
{
    public int id { get; set; }
    public string Name { get; set; }
}

public partial class MediaItem
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MediaItem()
    {
        this.Hotels = new HashSet<Hotel>();
        this.HotelFacilities = new HashSet<HotelFacility>();
        this.HotelImages = new HashSet<HotelImage>();
        this.VideoTranscripts = new HashSet<VideoTranscript>();
        this.VideoTranscripts1 = new HashSet<VideoTranscript>();
        this.VideoTranscripts2 = new HashSet<VideoTranscript>();
        this.Packages = new HashSet<Package>();
        this.MediaTags = new HashSet<MediaTag>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public string path { get; set; }
    public Nullable<int> MediaCategory_id { get; set; }
    public string mediaType { get; set; }
    public Nullable<System.DateTime> DateAdded { get; set; }
    public string MediumType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Hotel> Hotels { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HotelFacility> HotelFacilities { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HotelImage> HotelImages { get; set; }
    public virtual MediaCategory MediaCategory { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VideoTranscript> VideoTranscripts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VideoTranscript> VideoTranscripts1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VideoTranscript> VideoTranscripts2 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Package> Packages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MediaTag> MediaTags { get; set; }
}

public partial class MediaTag
{
    public int id { get; set; }
    public Nullable<int> MediaItem_id { get; set; }
    public Nullable<int> Tag_id { get; set; }

    public virtual MediaItem MediaItem { get; set; }
    public virtual Tag Tag { get; set; }
}

public partial class Multimediabank
{
    public int id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string DirectoryPath { get; set; }
    public string IndexFilePath { get; set; }
}

public partial class Package
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Package()
    {
        this.DreamLayouts = new HashSet<DreamLayout>();
        this.PackageDetails = new HashSet<PackageDetail>();
    }

    public int id { get; set; }
    public string PackageName { get; set; }
    public Nullable<int> MediaItem_id { get; set; }
    public string Description { get; set; }
    public bool IsFeatured { get; set; }
    public bool IsDefault { get; set; }
    public bool IsPublished { get; set; }
    public Nullable<int> LikeSeed { get; set; }
    public Nullable<int> PackageTypeID { get; set; }
    public string AspNetUserID { get; set; }
    public Nullable<System.DateTime> CreatedOn { get; set; }
    public string EditedBy { get; set; }
    public Nullable<System.DateTime> EditedOn { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DreamLayout> DreamLayouts { get; set; }
    public virtual PackageType PackageType { get; set; }
    public virtual MediaItem MediaItem { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageDetail> PackageDetails { get; set; }
}

public partial class PackageDetail
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PackageDetail()
    {
        this.AlharmainUserPackages = new HashSet<AlharmainUserPackage>();
        this.DiscountPackages = new HashSet<DiscountPackage>();
        this.PackageItenryDetails = new HashSet<PackageItenryDetail>();
    }

    public int id { get; set; }
    public int PackageID { get; set; }
    public int hotelIDMakkah { get; set; }
    public int nightsInMakkah { get; set; }
    public int hotelIDMadina { get; set; }
    public int nightsInMadina { get; set; }
    public bool returnFlight { get; set; }
    public Nullable<int> departureFlightID { get; set; }
    public Nullable<int> returnFlightID { get; set; }
    public bool isTransportAvailable { get; set; }
    public Nullable<int> transportID { get; set; }
    public bool isZiaratAvailable { get; set; }
    public Nullable<int> ziaratID { get; set; }
    public bool isVisaAvailable { get; set; }
    public Nullable<int> visaID { get; set; }
    public int additionalExpense { get; set; }
    public string additionalDetail { get; set; }
    public bool isAirLineAvailable { get; set; }
    public string packageType { get; set; }
    public Nullable<System.DateTime> startDate { get; set; }
    public double minRange { get; set; }
    public double maxRange { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AlharmainUserPackage> AlharmainUserPackages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DiscountPackage> DiscountPackages { get; set; }
    public virtual Flight Flight { get; set; }
    public virtual Flight Flight1 { get; set; }
    public virtual Hotel Hotel { get; set; }
    public virtual Hotel Hotel1 { get; set; }
    public virtual Package Package { get; set; }
    public virtual TransPort TransPort { get; set; }
    public virtual VisaPackage VisaPackage { get; set; }
    public virtual Ziarat Ziarat { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageItenryDetail> PackageItenryDetails { get; set; }
}

public partial class PackageItenryDetail
{
    public int id { get; set; }
    public string cityName { get; set; }
    public int nights { get; set; }
    public int packageDetailID { get; set; }
    public string alharmainUserID { get; set; }
    public int hotelID { get; set; }
    public Nullable<int> transportID { get; set; }

    public virtual Hotel Hotel { get; set; }
    public virtual TransPort TransPort { get; set; }
    public virtual PackageDetail PackageDetail { get; set; }
}

public partial class PackageTag
{
    public int id { get; set; }
    public Nullable<int> Package_id { get; set; }
    public Nullable<int> Tag_id { get; set; }

    public virtual Tag Tag { get; set; }
}

public partial class PackageType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PackageType()
    {
        this.Packages = new HashSet<Package>();
    }

    public int id { get; set; }
    public string Name { get; set; }
    public string DetailPath { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Package> Packages { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Tag
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tag()
    {
        this.PackageTags = new HashSet<PackageTag>();
        this.MediaTags = new HashSet<MediaTag>();
    }

    public int id { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageTag> PackageTags { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MediaTag> MediaTags { get; set; }
}

public partial class TransPort
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TransPort()
    {
        this.PackageItenryDetails = new HashSet<PackageItenryDetail>();
        this.PackageDetails = new HashSet<PackageDetail>();
    }

    public int id { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageItenryDetail> PackageItenryDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageDetail> PackageDetails { get; set; }
}

public partial class VideoTranscript
{
    public int id { get; set; }
    public Nullable<int> MediaItem_id { get; set; }
    public Nullable<decimal> TimeStamp { get; set; }
    public string Text { get; set; }

    public virtual MediaItem MediaItem { get; set; }
    public virtual MediaItem MediaItem1 { get; set; }
    public virtual MediaItem MediaItem2 { get; set; }
}

public partial class VisaPackage
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public VisaPackage()
    {
        this.PackageDetails = new HashSet<PackageDetail>();
    }

    public int id { get; set; }
    public string visaTitle { get; set; }
    public double amount { get; set; }
    public System.DateTime issueDate { get; set; }
    public System.DateTime expireDate { get; set; }
    public string AspNetUserID { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageDetail> PackageDetails { get; set; }
}

public partial class Ziarat
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ziarat()
    {
        this.PackageDetails = new HashSet<PackageDetail>();
    }

    public int id { get; set; }
    public string text { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PackageDetail> PackageDetails { get; set; }
}
